language: objective-c
osx_image: xcode7.2
before_install:
  - (ruby --version)
  - sudo chown -R travis ~/Library/RubyMotion
  - mkdir -p ~/Library/RubyMotion/build
  - sudo motion update
gemfile:
  - Gemfile
script:
  - gem install bundler
  - bundle install --jobs=3 --retry=3
  - bundle exec rake clean
  - bundle exec rake spec
  - bundle exec rake spec platform=osx
